import type { IPackRepository } from '$gathering/IPackRepository';
import type { Pack } from '$gathering/Pack';

export function createPackRepository(): IPackRepository {
  return thePackRepository;
}

class PackRepository implements IPackRepository {
  getAllPacks(): Iterable<Pack> {
    return [
      'A Light in the Fog',
      'A Phantom of Truth',
      'A Thousand Shapes of Horror',
      'Barkham Horror: The Meddling of Meowlathotep',
      'Before the Black Throne',
      'Black Stars Rise',
      'Blood on the Altar',
      'Carnevale of Horrors',
      'Core Set',
      'Curse of the Rougarou',
      'Dark Side of the Moon',
      'Devil Reef',
      'Dim Carcosa',
      'Echoes of the Past',
      'Edge of the Earth Campaign Expansion',
      'Edge of the Earth Investigator Expansion',
      'For the Greater Good',
      'Fortune and Folly',
      'Guardians of the Abyss',
      'Harvey Walters Investigator Starter Deck',
      'Heart of the Elders',
      'Horror in High Gear',
      'In the Clutches of Chaos',
      'In Too Deep',
      'Into the Maelstrom',
      'Jacqueline Fine Investigator Starter Deck',
      'Lost in Time and Space',
      'Machinations Through Time',
      'Murder at the Excelsior Hotel',
      'Nathaniel Cho Investigator Starter Deck',
      'Point of No Return',
      'Return to the Circle Undone',
      'Return to the Dunwich Legacy',
      'Return to the Forgotten Age',
      'Return to the Night of the Zealot',
      'Return to the Path to Carcosa',
      'Revised Core Set',
      'Shattered Aeons',
      'Stella Clark Investigator Starter Deck',
      'The Blob That Ate Everything',
      'The Boundary Beyond',
      'The Circle Undone Campaign Expansion',
      'The Circle Undone Investigator Expansion',
      'The Circle Undone',
      'The City of Archives',
      'The Depths of Yoth',
      'The Dream-Eaters',
      'The Dunwich Legacy Campaign Expansion',
      'The Dunwich Legacy Investigator Expansion',
      'The Dunwich Legacy',
      'The Essex County Express',
      'The Feast of Hemlock Vale Campaign Expansion',
      'The Feast of Hemlock Vale Investigator Expansion',
      'The Forgotten Age Campaign Expansion',
      'The Forgotten Age Investigator Expansion',
      'The Forgotten Age',
      'The Innsmouth Conspiracy',
      'The Labyrinths of Lunacy',
      'The Lair of Dagon',
      'The Miskatonic Museum',
      'The Pallid Mask',
      'The Path to Carcosa Campaign Expansion',
      'The Path to Carcosa Investigator Expansion',
      'The Path to Carcosa',
      'The Scarlet Keys Campaign Expansion',
      'The Scarlet Keys Investigator Expansion',
      'The Search for Kadath',
      'The Secret Name',
      'The Unspeakable Oath',
      'The Wages of Sin',
      'Threads of Fate',
      'Undimensioned and Unseen',
      'Union and Disillusion',
      'War of the Outer Gods',
      'Weaver of the Cosmos',
      'Where Doom Awaits',
      'Where the Gods Dwell',
      'Winifred Habbamock Investigator Starter Deck',
    ];
  }
}

// no need to get many instance of static data.
const thePackRepository = new PackRepository();
