import type { IPackRepository } from '$gathering/IPackRepository';
import type { Pack } from '$gathering/Pack';

export function createPackRepository(): IPackRepository {
  return thePackRepository;
}

class PackRepository implements IPackRepository {
  getAllPacks(): Iterable<Pack> {
    return [
      'Core Set',
      'Revised Core Set',
      'Return to the Night of the Zealot',
      'The Dunwich Legacy Investigator Expansion',
      'The Dunwich Legacy Campaign Expansion',
      'Return to the Dunwich Legacy',
      'The Dunwich Legacy',
      'The Miskatonic Museum',
      'The Essex County Express',
      'Blood on the Altar',
      'Undimensioned and Unseen',
      'Where Doom Awaits',
      'Lost in Time and Space',
      'The Path to Carcosa Investigator Expansion',
      'The Path to Carcosa Campaign Expansion',
      'Return to the Path to Carcosa',
      'The Path to Carcosa',
      'Echoes of the Past',
      'The Unspeakable Oath',
      'A Phantom of Truth',
      'The Pallid Mask',
      'Black Stars Rise',
      'Dim Carcosa',
      'The Forgotten Age Investigator Expansion',
      'The Forgotten Age Campaign Expansion',
      'Return to the Forgotten Age',
      'The Forgotten Age',
      'Threads of Fate',
      'The Boundary Beyond',
      'Heart of the Elders',
      'The City of Archives',
      'The Depths of Yoth',
      'Shattered Aeons',
      'Return to the Forgotten Age',
      'The Circle Undone Investigator Expansion',
      'The Circle Undone Campaign Expansion',
      'Return to the Circle Undone',
      'The Circle Undone',
      'The Secret Name',
      'The Wages of Sin',
      'For the Greater Good',
      'Union and Disillusion',
      'In the Clutches of Chaos',
      'Before the Black Throne',
      'The Dream-Eaters',
      'The Search for Kadath',
      'A Thousand Shapes of Horror',
      'Dark Side of the Moon',
      'Point of No Return',
      'Where the Gods Dwell',
      'Weaver of the Cosmos',
      'The Innsmouth Conspiracy',
      'In Too Deep',
      'Devil Reef',
      'Horror in High Gear',
      'A Light in the Fog',
      'The Lair of Dagon',
      'Into the Maelstrom',
      'Edge of the Earth Investigator Expansion',
      'Edge of the Earth Campaign Expansion',
      'The Scarlet Keys Campaign Expansion',
      'The Scarlet Keys Investigator Expansion',
      'The Feast of Hemlock Vale Investigator Expansion',
      'The Feast of Hemlock Vale Campaign Expansion',
      'Winifred Habbamock Investigator Starter Deck',
      'Nathaniel Cho Investigator Starter Deck',
      'Harvey Walters Investigator Starter Deck',
      'Jacqueline Fine Investigator Starter Deck',
      'Stella Clark Investigator Starter Deck',
      'Curse of the Rougarou',
      'Carnevale of Horrors',
      'The Labyrinths of Lunacy',
      'Guardians of the Abyss',
      'Murder at the Excelsior Hotel',
      'Barkham Horror: The Meddling of Meowlathotep',
      'The Blob That Ate Everything',
      'War of the Outer Gods',
      'Machinations Through Time',
      'Fortune and Folly',
    ];
  }
}

// no need to get many instance of static data.
const thePackRepository = new PackRepository();
