name: The Gathering CI

on: push

jobs:
  build:
    name: 'build, test, lint, ...'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.11.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test:coverage
      - run: pnpm run lint

      - name: Setup Graphviz (dot)
        uses: ts-graphviz/setup-graphviz@v2
      - name: Generate Architecture Diagrams
        run: pnpm arch
