name: The Gathering CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pnpm build
      - run: pnpm test:unit
      - run: pnpm lint
      - run: pnpm arch
